version: "3.3"

services:
  app:
    build: 
      context: ./
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app