name: Dev Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dev-check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch --no-tags --prune --depth=5 origin main
      - run: npm ci
      - run: npm run format
      - name: Commit format changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[BOT]: Auto format"
          branch: ${{ github.head_ref }}
      - run: npm run lint