name: Launch e2e tests

on:
  pull_request:
    branches: [main]

jobs:
  e2e-testing:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Fetch last content
        run: git fetch --no-tags --prune --depth=5 origin main

      - name: Install dependencies
        run: npm ci

      - name: Launch app on detached screen
        run: screen -d -m npm run dev

      - name: Launch e2e tests
        run: npm run e2e
