name: Web Server Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  web-server-check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build docker image
        run: docker build -t js-prod .

      - name: Launch container
        run: docker run -d -p 80:80 js-prod

      - name: Check availability
        # sleep 5s to wait for the web server to fully start
        run: sleep 5; if ! curl 127.0.0.1; then exit 1; else exit 0; fi
